# Form implementation generated from reading ui file 'd:\Code\Python\pyQT\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication,QMainWindow,QLabel,QWidget,QLineEdit,QPushButton,QVBoxLayout,QGraphicsColorizeEffect
from Ui_AcademicIntegrityChecker import AIC
from Ui_StreamingPaperWritingSystem import SPWS
import PDFSummarizerApp

# 导入配置管理
from config import get_api_key, get_base_url, get_model_name

my_api_key = get_api_key()
my_base_url = get_base_url()
my_model_name = get_model_name()

class AICMainWindow(QMainWindow,AIC):
    def __init__(self,parent =None):
        super(AICMainWindow,self).__init__(parent)
        self.setupUi(self)

class SPWSMainWindow(QMainWindow,SPWS):
    def __init__(self,parent =None):
        super(SPWSMainWindow,self).__init__(parent)
        self.setupUi(self)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(250, 170, 191, 31))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(250, 250, 191, 24))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(250, 340, 191, 24))
        self.pushButton3.setObjectName("pushButton3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 70, 111, 51))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.pushButton1.clicked.connect(self.open_new_window_SPWS)
        self.pushButton2.clicked.connect(self.open_new_window_PDFSummarizer)
        self.pushButton3.clicked.connect(self.open_new_window_AIC)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton1.setText(_translate("MainWindow", "师生协作写作➕爬虫推荐文献"))
        self.pushButton2.setText(_translate("MainWindow", "pdf总结器"))
        self.pushButton3.setText(_translate("MainWindow", "学术诚信检查➕写作助手"))
        self.label.setText(_translate("MainWindow", "是名字"))

    def open_new_window_SPWS(self):
        # 创建并显示新窗口
        self.new_window = SPWSMainWindow()
        self.new_window.show()
    
    def open_new_window_PDFSummarizer(self):
        # 创建并显示PDF Summarizer窗口
        PDFSummarizerApp.main()

    def open_new_window_AIC(self):
        # 创建并显示新窗口
        self.new_window = AICMainWindow()
        self.new_window.show()