# Form implementation generated from reading ui file 'd:\Code\Python\pyQT\StreamingPaperWritingSystem.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
# Form implementation generated from reading ui file 'd:\Code\Python\pyQT\StreamingPaperWritingSystem.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import openai
import sys
import time
import requests
import xml.etree.ElementTree as ET
from urllib.parse import quote
import re
from datetime import datetime, timedelta
from typing import List, Dict
from camel.agents import ChatAgent
from camel.models import ModelFactory
from camel.types import ModelPlatformType
from camel.utils import print_text_animated
from colorama import Fore, init
from camel.societies import RolePlaying
from dotenv import load_dotenv
import os
import json
from bs4 import BeautifulSoup
from datetime import datetime
from urllib.parse import quote
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QTextCursor, QTextCharFormat, QColor

# 初始化colorama
init(autoreset=True)
# 导入配置管理
from config import get_api_key, get_base_url, get_model_name

my_api_key = get_api_key()
my_base_url = get_base_url()
my_model_name = get_model_name()


class ArxivCrawler:
    """ArXiv论文爬虫 - 使用网页搜索"""

    def __init__(self,ptr):
        self.base_url = "https://arxiv.org/search/"
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        self.openai_client = openai.OpenAI(api_key=my_api_key, base_url=my_base_url)
        self.model_name = my_model_name
        self.spws_ptr = ptr  # 用于与SPWS交互
    def translate_query(self, query: str) -> str:
        """将中文查询词翻译为英文"""
        try:
            # 检查是否包含中文字符
            if any('\u4e00' <= char <= '\u9fff' for char in query):
                self.spws_ptr.append_colored_text(f"🔍 检测到中文查询词: {query}，正在翻译...","yellow")
                # 构建翻译提示
                prompt = f"请将以下中文查询词翻译为英文，用于学术文献搜索：\n{query}"
                response = self.openai_client.chat.completions.create(
                    model=self.model_name,
                    messages=[
                        {"role": "system", "content": "你是一名专业的学术翻译专家，需将中文准确译为英文学术关键词"},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=0.2,
                    max_tokens=100
                )
                # 提取翻译结果（去除可能的标点和多余空格）
                translation = response.choices[0].message.content.strip()
                # 处理可能的标点符号（如结尾的句号）
                if translation.endswith('.'):
                    translation = translation[:-1]
                self.spws_ptr.append_colored_text(f"✅ 翻译完成: {translation}","green")
                return translation
            return query  # 非中文直接返回原词
        except Exception as e:
            self.spws_ptr.append_colored_text(f"❌ 翻译失败: {e}，使用原词搜索","red")
            return query
    def search_papers(self, query: str, max_results: int = 50) -> List[Dict]:
        """
        从ArXiv搜索相关论文
        Args:
            query: 搜索关键词
            max_results: 最大返回结果数
        Returns:
            论文信息列表
        """
        translated_query = self.translate_query(query)
        self.spws_ptr.append_colored_text(f"🔍 正在ArXiv搜索: {translated_query}","yellow")

        papers = []
        page = 0
        per_page = 50  # ArXiv每页最多显示50篇论文

        try:
            while len(papers) < max_results:
                # 构建搜索URL
                params = {
                    'query': translated_query,
                    'searchtype': 'all',
                    'source': 'header',
                    'start': page * per_page
                }

                self.spws_ptr.append_colored_text(f"🌐 正在获取第 {page + 1} 页...","cyan")

                response = requests.get(self.base_url, params=params, headers=self.headers, timeout=30)
                response.raise_for_status()

                soup = BeautifulSoup(response.content, 'html.parser')

                # 查找论文条目
                paper_items = soup.find_all('li', class_='arxiv-result')

                if not paper_items:
                    self.spws_ptr.append_colored_text(f"⚠️  第 {page + 1} 页没有找到论文，停止搜索","yellow")
                    break

                self.spws_ptr.append_colored_text(f"✅ 第 {page + 1} 页找到 {len(paper_items)} 篇论文","green")

                # 解析每篇论文
                for item in paper_items:
                    if len(papers) >= max_results:
                        break

                    paper_info = self._parse_paper_item(item)
                    if paper_info:
                        papers.append(paper_info)

                # 检查是否还有更多页面
                if len(paper_items) < per_page:
                    break

                page += 1
                time.sleep(1)  # 避免请求过快

        except requests.RequestException as e:
            self.spws_ptr.append_colored_text(f"❌ 网络请求失败: {e}","red")
        except Exception as e:
            self.spws_ptr.append_colored_text(f"❌ 解析失败: {e}","red")

        self.spws_ptr.append_colored_text(f"✅ 总共找到 {len(papers)} 篇相关论文","green")
        return papers

    def _parse_paper_item(self, item) -> Dict:
        """解析单个论文条目"""
        try:
            # 获取标题
            title = item.find('p', class_="title is-5 mathjax").text
            if title:
                # print(title)
                pass
            else:
                title = "未知标题"
                self.spws_ptr.textEdit.append("获取标题失败")

            # 获取摘要链接
            abs_link = item.find('p', class_='list-title is-inline-block').find('a')['href']
            if abs_link:
                # print(abs_link)
                pass
            else:
                abs_link = "#"
                self.spws_ptr.textEdit.append("获取abs_link失败")

            # 获取ArXiv ID
            arxiv_id = item.find('p', class_='list-title is-inline-block').find('a').text.split(':')[1]
            if arxiv_id:
                # print(arxiv_id)
                pass
            else:
                arxiv_id = "未知ID"
                self.spws_ptr.textEdit.append("获取arxiv_id失败")

            # 构建PDF链接
            pdf_link = f"https://arxiv.org/pdf/{arxiv_id}" if arxiv_id else "#"

            # 获取作者
            authors = []
            authors_elem = item.find('p', class_='authors')
            if authors_elem:
                author_links = authors_elem.find_all('a')
                for author_link in author_links:
                    authors.append(author_link.text.strip())

            # 获取摘要
            abstract_elem = item.find('p', class_='abstract')
            if abstract_elem:
                abstract_text = abstract_elem.text.strip()
                if abstract_text.startswith('Abstract:'):
                    summary = abstract_text[9:].strip()
            else:
                summary = "无摘要"

            # 获取发布日期
            submitted_elem = item.find('p', class_='is-size-7')
            published_date = submitted_elem.text.strip() if submitted_elem else "未知日期"

            # 获取分类信息
            categories = []
            subject_elem = item.find('div', class_='tags is-inline-block')
            if subject_elem:
                tag_links = subject_elem.find_all(class_='tag')
                for tag_link in tag_links:
                    category = tag_link.text.strip()
                    if category:
                        categories.append(category)

            # 限制摘要长度
            if len(summary) > 500:
                summary = summary[:500] + '...'

            return {
                'title': title,
                'authors': authors,
                'summary': summary,
                'published_date': published_date,
                'arxiv_id': arxiv_id,
                'pdf_link': pdf_link,
                'abs_link': abs_link,
                'categories': categories,
                'authors_str': ', '.join(authors[:3]) + (' et al.' if len(authors) > 3 else '')
            }

        except Exception as e:
            self.spws_ptr.append_colored_text(f"❌ 解析论文条目失败: {e}","red")
            return None

class PaperValueAssessmentAgent:
    """论文价值评估代理"""

    def __init__(self,ptr):
        self.client = openai.OpenAI(api_key=my_api_key, base_url=my_base_url)
        self.model = my_model_name
        self.spws_ptr = ptr  # 用于与SPWS交互

    def assess_papers(self, papers: List[Dict], theme: str, subject: str, outline: str) -> List[Dict]:
        """
        评估论文价值并排序

        Args:
            papers: 论文列表
            theme: 论文主题方向
            subject: 具体主题
            outline: 论文提纲

        Returns:
            按价值排序的论文列表
        """
        self.spws_ptr.append_colored_text(f"🎯 正在评估 {len(papers)} 篇论文的参考价值...","yellow")

        # 构建评估提示
        assessment_prompt = self._build_assessment_prompt(papers, theme, subject, outline)

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system",
                    "content": "你是一名学术评估专家，需要根据论文与给定主题的相关性、引用价值、研究质量等因素对论文进行评分排序。"},
                    {"role": "user", "content": assessment_prompt}
                ],
                temperature=0.3,
                max_tokens=4096
            )

            assessment_result = response.choices[0].message.content
            ranked_papers = self._parse_assessment_result(assessment_result, papers)

            self.spws_ptr.append_colored_text(f"✅ 论文价值评估完成，推荐前 {min(10, len(ranked_papers))} 篇","green")
            return ranked_papers[:10]  # 返回前10篇

        except Exception as e:
            self.spws_ptr.append_colored_text(f"❌ 论文评估失败: {e}","red")
            # 如果评估失败，按发布时间排序返回
            return sorted(papers, key=lambda x: x['published_date'], reverse=True)[:10]

    def _build_assessment_prompt(self, papers: List[Dict], theme: str, subject: str, outline: str) -> str:
        """构建评估提示"""
        papers_info = ""
        for i, paper in enumerate(papers, 1):
            papers_info += f"""
论文{i}:
- 标题: {paper['title']}
- 作者: {paper['authors_str']}
- 摘要: {paper['summary']}
- 发布时间: {paper['published_date']}
- 分类: {', '.join(paper['categories'][:3])}
---
"""

        prompt = f"""
请评估以下论文对于"{theme}"领域中"{subject}"主题研究的参考价值。

研究提纲:
{outline}

待评估论文:
{papers_info}

评估标准:
1. 与研究主题的相关性 (40%)
2. 研究方法的创新性和严谨性 (25%)
3. 发表时间的新颖性 (20%)
4. 作者权威性和期刊质量 (15%)

请按以下JSON格式输出评估结果，包含每篇论文的评分(1-10分)和排序:
```json
{{
  "rankings": [
    {{
      "paper_index": 1,
      "score": 8.5,
      "reasoning": "相关性高，方法创新..."
    }},
    ...
  ]
}}
```

请确保JSON格式正确，按评分从高到低排序。
"""
        return prompt

    def _parse_assessment_result(self, assessment_result: str, papers: List[Dict]) -> List[Dict]:
        """解析评估结果"""
        try:
            # 提取JSON部分
            json_match = re.search(r'```json\s*(\{.*?\})\s*```', assessment_result, re.DOTALL)
            if json_match:
                json_str = json_match.group(1)
                assessment_data = json.loads(json_str)

                # 按评估结果排序论文
                ranked_papers = []
                for ranking in assessment_data.get('rankings', []):
                    paper_index = ranking.get('paper_index', 1) - 1  # 转换为0基索引
                    if 0 <= paper_index < len(papers):
                        paper = papers[paper_index].copy()
                        paper['assessment_score'] = ranking.get('score', 0)
                        paper['assessment_reasoning'] = ranking.get('reasoning', '')
                        ranked_papers.append(paper)

                return ranked_papers

        except (json.JSONDecodeError, KeyError) as e:
            self.spws_ptr.append_colored_text(f"⚠️  评估结果解析失败，使用默认排序: {e}","yellow")

        # 如果解析失败，按发布时间排序
        return sorted(papers, key=lambda x: x['published_date'], reverse=True)

class StreamingChatAgent:
    """带流式响应功能的聊天代理"""

    def __init__(self, system_message="", output_language="zh",ptr=None):
        self.client = openai.OpenAI(api_key=my_api_key, base_url=my_base_url)
        self.model = my_model_name
        self.system_message = system_message
        self.output_language = output_language
        self.conversation_history = []
        self.spws_ptr = ptr  # 用于与SPWS交互

        # 添加系统消息到对话历史
        if system_message:
            self.conversation_history.append({"role": "system", "content": system_message})

    def stream_step(self, message: str, typing_delay: float = 0.001, show_role_prefix: str = ""):
        """流式响应处理"""
        # 添加用户消息到历史
        self.conversation_history.append({"role": "user", "content": message})

        try:
            # 创建流式请求
            stream = self.client.chat.completions.create(
                model=self.model,
                messages=self.conversation_history,
                temperature=0.8,
                max_tokens=8192,
                stream=True  # 启用流式输出
            )

            full_response = ""
            if show_role_prefix:
                self.spws_ptr.append_text(show_role_prefix, color="blue", newline=False)

            # 逐块处理流式响应
            for chunk in stream:
                if chunk.choices[0].delta.content is not None:
                    content = chunk.choices[0].delta.content
                    full_response += content

                    cursor = self.spws_ptr.textEdit.textCursor()
                    cursor.movePosition(QtGui.QTextCursor.MoveOperation.End)
                    
                    for char in content:
                        # 为每个字符创建新的格式并设置为黑色
                        char_format = QTextCharFormat()
                        char_format.setForeground(QColor("black"))
                        
                        # 插入单个字符并应用格式
                        cursor.insertText(char, char_format)
                        
                        # 确保UI更新
                        QtCore.QCoreApplication.processEvents()
                        
                        # 控制输出速度
                        time.sleep(typing_delay)
                    
                    # 确保光标可见
                    self.spws_ptr.textEdit.setTextCursor(cursor)
                    self.spws_ptr.textEdit.ensureCursorVisible()
                    # # 打字机效果输出
                    # for char in content:
                    #     sys.stdout.write(char)
                    #     sys.stdout.flush()
                    #     time.sleep(typing_delay)

            self.spws_ptr.textEdit.append('\n')

            # 保存完整响应到对话历史
            self.conversation_history.append({"role": "assistant", "content": full_response})
            return full_response

        except Exception as e:
            self.spws_ptr.append_colored_text(f"❌ 流式请求失败: {e}","red")
            return f"请求失败: {e}"


class StreamingPaperWritingSystem:
    """带流式响应的论文写作系统"""

    def __init__(self,ptr):
        self.camel_model = ModelFactory.create(
            model_platform = ModelPlatformType.OPENAI,
            model_type=my_model_name,
            url=my_base_url,
            api_key=my_api_key,
            model_config_dict={
                "max_tokens": 4096
            }
        )
        self.spws_ptr = ptr  # 用于与SPWS交互

        # 初始化变量
        self.theme = ""
        self.subject = ""
        self.outline = ""
        self.arxiv_crawler = ArxivCrawler(ptr=self.spws_ptr)
        self.value_assessor = PaperValueAssessmentAgent(ptr=self.spws_ptr)

    def generate_outline(self):

        # 创建提纲生成Agent
        outline_agent = StreamingChatAgent(
            system_message="你是一名学术写作专家，需生成包含以下要素的论文提纲：\n"
                           "1. 严格遵循IMRaD结构（引言、方法、结果、讨论）\n"
                           "2. 每个章节至少包含2个子章节\n"
                           "3. 用Markdown格式输出层级标题",
            output_language="zh",
            ptr=self.spws_ptr
        )
        self.spws_ptr.append_colored_text("\n🔄 正在生成提纲...","yellow")

        self.outline = outline_agent.stream_step(
            f"请生成关于{self.theme}的有关{self.subject}内容的论文提纲",
            typing_delay=0.01,
            show_role_prefix=""
        )

    def start_collaborative_writing(self, rounds=3):
        """开始协作写作过程"""
        self.spws_ptr.append_colored_text(f"\n🎯 开始师生协作优化（共{rounds}轮）","magenta")
        self.spws_ptr.textEdit.append("=" * 60)

        # 创建流式代理
        assistant_agent = StreamingChatAgent(
            system_message=f"""你是一名要求严格的导师(RoleType:ASSISTANT)，必须按以下规则指导：
                            1. 用'逻辑问题X：...'格式指出提纲缺陷
                            2. 每次只提1个核心问题
                            3. 避免直接给出答案
                            4. 重点关注{self.theme}领域的{self.subject}专业问题""",
            output_language="zh",
            ptr=self.spws_ptr
        )

        user_agent = StreamingChatAgent(
            system_message=f"""你是学生（RoleType.USER），你正在撰写关于{self.theme}的有关{self.subject}内容的论文，你的任务是：
                            1. 根据导师的意见对提纲作出修改
                            2. 最终生成修订版提纲""",
            output_language="zh",
            ptr=self.spws_ptr
        )

        # 学生发送初始消息
        user_msg = f"以下是我的论文提纲，请批评指正：\n\n{self.outline}"

        for i in range(rounds):
            # 导师流式回复
            self.spws_ptr.append_colored_text(f"\n👨‍🏫 导师 第{i + 1}轮:","blue")
            assistant_msg = assistant_agent.stream_step(
                user_msg,
                typing_delay=0.001,
                show_role_prefix=""
            )

            # 最后一轮指导后直接生成最终提纲
            if i + 1 == rounds:
                assistant_msg = assistant_msg + "注意！这一版修改完毕后请*直接*输出完整的可以直接拷贝的md格式提纲！否则不予通过！"

            # 学生流式回复
            self.spws_ptr.append_colored_text(f"\n🧑‍🎓 学生 第{i + 1}轮回应:","green")
            user_msg = user_agent.stream_step(
                assistant_msg,
                typing_delay=0.001,
                show_role_prefix=""
            )

        self.spws_ptr.append_colored_text("\n🎉 协作优化完成！","cyan")
        return user_msg

    def save_final_outline(self, final_outline):
        """保存最终提纲"""
        filename = f"{self.theme}_{self.subject}_论文提纲.md"
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(f"# {self.theme} - {self.subject} 论文提纲\n\n")
                f.write(f"**生成时间**: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
                f.write("## 最终优化提纲\n\n")
                f.write(final_outline)

            self.spws_ptr.append_colored_text(f"\n💾 最终提纲已保存至: {filename}","green")
        except Exception as e:
            self.spws_ptr.append_colored_text(f"\n❌ 保存失败: {e}","red")

    def search_and_save_references(self, final_outline):
        """使用ArXiv爬虫搜索并评估参考文献"""
        self.spws_ptr.append_colored_text("\n🔍 正在从ArXiv搜索相关论文...","yellow")

        # 构建搜索关键词
        search_query = f"{self.subject} {self.theme}"

        # 爬取论文
        papers = self.arxiv_crawler.search_papers(search_query, max_results=50)

        if not papers:
            self.spws_ptr.append_colored_text("❌ 未找到相关论文","red")
            return

        # 评估论文价值
        ranked_papers = self.value_assessor.assess_papers(papers, self.theme, self.subject, final_outline)

        # 保存参考文献
        filename = f"{self.theme}_{self.subject}_参考文献.md"
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                f.write(f"# {self.theme} - {self.subject} 参考文献\n\n")
                f.write(f"**生成时间**: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"**搜索关键词**: {search_query}\n")
                f.write(f"**总共找到**: {len(papers)} 篇论文\n")
                f.write(f"**推荐**: 前 {len(ranked_papers)} 篇高价值论文\n\n")

                f.write("## 推荐文献列表\n\n")

                for i, paper in enumerate(ranked_papers, 1):
                    f.write(f"### {i}. {paper['title']}\n\n")
                    f.write(f"**作者**: {paper['authors_str']}\n\n")
                    f.write(f"**发布时间**: {paper['published_date']}\n\n")
                    f.write(f"**ArXiv ID**: {paper['arxiv_id']}\n\n")
                    f.write(f"**分类**: {', '.join(paper['categories'][:3])}\n\n")
                    f.write(f"**链接**: \n")
                    f.write(f"- [论文摘要]({paper['abs_link']})\n")
                    f.write(f"- [PDF下载]({paper['pdf_link']})\n\n")
                    f.write(f"**摘要**: {paper['summary']}\n\n")

                    if 'assessment_score' in paper:
                        f.write(f"**评估分数**: {paper['assessment_score']}/10\n\n")
                    if 'assessment_reasoning' in paper:
                        f.write(f"**推荐理由**: {paper['assessment_reasoning']}\n\n")

                    f.write("---\n\n")

            self.spws_ptr.append_colored_text(f"\n💾 参考文献已保存至: {filename}","green")
            self.spws_ptr.append_colored_text(f"📊 共推荐 {len(ranked_papers)} 篇高质量论文","cyan")

        except Exception as e:
            self.spws_ptr.append_colored_text(f"\n❌ 保存失败: {e}","red")

    def run(self):
        try:
            # 1. 生成提纲
            self.generate_outline()
            # 2. 开始协作优化
            final_outline = self.start_collaborative_writing(rounds=1)
            # 3. 保存最终提纲
            self.save_final_outline(final_outline)
            # 4. 使用ArXiv爬虫查找并评估参考文献
            self.search_and_save_references(final_outline)

        except KeyboardInterrupt:
            self.spws_ptr.append_colored_text("\n\n⚠️  用户中断程序","yellow")
        except Exception as e:
            self.spws_ptr.append_colored_text(f"\n❌ 系统错误: {e}","red")

class SPWS(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("师生协作写作平台+集成爬虫推荐文献功能")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 631, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_1 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout.addWidget(self.lineEdit_1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 681, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(60, 210, 691, 321))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(710, 80, 75, 24))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.on_pushbutton_clicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "师生协作写作平台+集成爬虫推荐文献功能"))
        self.label.setText(_translate("MainWindow", "论文主要方向（如：医学、数学、语文等）："))
        self.label_2.setText(_translate("MainWindow", "论文主题（如：心血管疾病、微积分、古代诗词等）："))
        self.pushButton.setText(_translate("MainWindow", "生成"))

    def on_pushbutton_clicked(self):
        theme = self.lineEdit_1.text()
        subject = self.lineEdit_2.text()
        if not theme or not subject:
            self.textEdit.setText("请填写论文主要方向和主题！")
            return

        # 创建论文写作系统实例
        spws = StreamingPaperWritingSystem(ptr=self)
        spws.theme = theme
        spws.subject = subject

        # 运行论文写作流程
        spws.run()

    # 在 SPWS 类中添加一个方法来处理带颜色的文本输出
    def append_colored_text(self, text, color_name="black"):
        """向 textEdit 添加带颜色的文本"""
        cursor = self.textEdit.textCursor()
        cursor.movePosition(QtGui.QTextCursor.MoveOperation.End)
        
        # 设置文本格式
        fmt = QtGui.QTextCharFormat()
        if color_name == "red":
            fmt.setForeground(QtGui.QColor("#FF0000"))  # 红色
        elif color_name == "green":
            fmt.setForeground(QtGui.QColor("#00FF00"))  # 绿色
        elif color_name == "yellow":
            fmt.setForeground(QtGui.QColor("#FFD700"))  # 黄色
        elif color_name == "blue":
            fmt.setForeground(QtGui.QColor("#0000FF"))  # 蓝色
        elif color_name == "magenta":
            fmt.setForeground(QtGui.QColor("#FF00FF"))  # 洋红
        elif color_name == "cyan":
            fmt.setForeground(QtGui.QColor("#00FFFF"))  # 青色
        else:
            fmt.setForeground(QtGui.QColor("#000000"))  # 默认黑色
        
        # 应用格式并插入文本
        cursor.insertText(text + "\n", fmt)
        self.textEdit.setTextCursor(cursor)
        self.textEdit.ensureCursorVisible()  # 自动滚动到底部
    
    def append_text(self, text, color="black", newline=True):
        """向 textEdit 添加文本（可选择颜色和是否换行）"""
        cursor = self.textEdit.textCursor()
        cursor.movePosition(QtGui.QTextCursor.MoveOperation.End)
        
        # 设置文本格式
        fmt = QtGui.QTextCharFormat()
        if color == "red":
            fmt.setForeground(QtGui.QColor("#FF0000"))  # 红色
        elif color == "green":
            fmt.setForeground(QtGui.QColor("#00FF00"))  # 绿色
        elif color == "yellow":
            fmt.setForeground(QtGui.QColor("#FFD700"))  # 黄色
        elif color == "blue":
            fmt.setForeground(QtGui.QColor("#0000FF"))  # 蓝色
        elif color == "magenta":
            fmt.setForeground(QtGui.QColor("#FF00FF"))  # 洋红
        elif color == "cyan":
            fmt.setForeground(QtGui.QColor("#00FFFF"))  # 青色
        else:
            fmt.setForeground(QtGui.QColor("#000000"))  # 默认黑色
        
        # 插入文本
        cursor.insertText(text, fmt)
        if newline:
            cursor.insertText("\n")
        
        self.textEdit.setTextCursor(cursor)
        self.textEdit.ensureCursorVisible()

